name: clean_architecture_tdd
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.8.6
  data_connection_checker: ^0.3.4
  equatable: ^1.2.5
  flutter_bloc: ^0.21.0
  get_it: ^2.0.1
  http: ^0.12.0+2
  shared_preferences: ^0.5.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.0

flutter:
  uses-material-design: true
